<?xml version="1.0"?>
<robot name="ground_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="base_width" value="0.6"/>
  <xacro:property name="base_length" value="0.8"/>
  <xacro:property name="base_height" value="0.1"/>
  
  <xacro:property name="wheel_z_offset" value="${wheel_radius}"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <geometry >
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
 
      
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="${base_length/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>
      <link name="marker">
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <mass value="0.0001" />
            <inertia ixx="0.00" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0001" />
        </inertial>
         <visual name="marker">
            <origin rpy="0.0 -1.570796327 0.0" />
            <geometry>
                <mesh filename="$(find robots_description)/meshes/Marker0.obj" scale="1.0 1.0 1.0" />
            </geometry>
        </visual> 
    </link>
  <joint name="aruco" type="fixed">
     <parent link="base_link"/>
      <child link="marker"/>
      <origin xyz="0 -${base_width/2-0.05} ${base_height/2+0.05}" rpy="0 0 0"/>
  </joint>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="1.5708 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>
  </xacro:macro>
    
  

  <xacro:wheel name="wheel_front_left" x="${base_length/2}" y="${base_width/2}" z="-${wheel_radius}"/>
  <xacro:wheel name="wheel_front_right" x="${base_length/2}" y="-${base_width/2}" z="-${wheel_radius}"/>
  <xacro:wheel name="wheel_back_left" x="-${base_length/2}" y="${base_width/2}" z="-${wheel_radius}"/>
  <xacro:wheel name="wheel_back_right" x="-${base_length/2}" y="-${base_width/2}" z="-${wheel_radius}"/>





  
  <!-- Differential Drive Plugin -->
  <!-- <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <wheelSeparation>${base_width}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <wheelTorque>5.0</wheelTorque>
      <commandTopic>/cmd_vel</commandTopic>
      <odometryTopic>/odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishTf>true</publishTf>
      <leftJoint>wheel_front_left_joint</leftJoint>
      <rightJoint>wheel_front_right_joint</rightJoint>
    </plugin>
  </gazebo> -->

  <gazebo>
    <plugin name="wheel_drive_controller" filename="libgazebo_ros_diff_drive.so">
        <!-- wheels -->
        <num_wheel_pairs>2</num_wheel_pairs>
        <left_joint>wheel_front_left_joint</left_joint>
        <right_joint>wheel_front_right_joint</right_joint>
        <left_joint>wheel_back_left_joint</left_joint>
        <right_joint>wheel_back_right_joint</right_joint>

        <!-- kinematics -->
        <wheel_separation>${base_width}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>



        <!-- Limits -->
        <max_wheel_torque>200.0</max_wheel_torque>
        <max_wheel_acceleration>10.0</max_wheel_acceleration>

        <!-- Output -->
        <odometry_frame>odom</odometry_frame>
        <robot_base_frame>base_link</robot_base_frame>

        <!-- topic & re remappings -->
        <ros>
            <namespace>/ground_robot</namespace>
            <argument>/cmd_vel:=cmd_vel</argument>
            <argument>/odom:=odom</argument>
        </ros >

        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <update_rate>100.0</update_rate>
    </plugin>
</gazebo>


</robot>
